### ISSUE TITLE
iPad is detected as a mobile AND a tablet

### ISSUE THREAD

**Issue by eved42** [bes89/mobiledetect-twig-extension#2]
Hello,

I've tried your extension on a symfony 3.0 project with an iPad.

When I use : 
`{% if is_mobile() %}<p>Mobile !</p>{% endif %}`
`{% if is_tablet() %}<p>Tablet !</p>{% endif %}`

Both paragraphs appear... Is it normal ?

Thanks !

**Comment by eved42** [comment]
I found a way to make the difference between a mobile and a tablet : 

// Detect a mobile
`{% if is_mobile() and is_tablet() == false %} ... {% endif %}`

**Comment by bes89** [comment]
Thank you for sharing your solution! :+1: 

PS: you could use the great `if not x` or `if x is false` [if-syntax](http://twig.sensiolabs.org/doc/tags/if.html) of twig ;-)
