### ISSUE TITLE
Twig 2.x?

### ISSUE THREAD

**Issue by artjomsimon** [bes89/mobiledetect-twig-extension#3]
Hey @bes89, first and foremost, thanks for your effort providing this extension.

Do you have any plans to update the code to make it compatible with Twig 2.x?

Thanks,

Artjom

**Comment by bes89** [comment]
Hi @artjomsimon,

not planned but i'll take a look at the changes in twig 2 and update the extension accordingly

Maybe within the next 2 weeks

**Comment by elernonelma** [comment]
Did you manage to get some time to look at it?

**Comment by bes89** [comment]
Now, yes. 
No changes needed, just set version to `1.*` in your `composer.json` and update. Reopen this issue if errors occur.
Next time feel free to create a PR #opensource :grinning:
